version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "stable/9"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "stable/9"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "camunda-schema-bundler"
        versions: [">=2.0.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "stable/9"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
